USE Master
GO

CREATE SERVER ROLE AOAG AUTHORIZATION [WIN-KIAGK4GN1MJ\Administrator] ;
GO

GRANT ALTER ANY AVAILABILITY GROUP TO AOAG ;

GRANT ALTER ANY ENDPOINT TO AOAG ;

GRANT CREATE AVAILABILITY GROUP TO AOAG ;

GRANT CREATE ENDPOINT TO AOAG ;
GO
