USE Master
GO

CREATE LOGIN Danielle 
    WITH PASSWORD=N'Pa$$w0rd' MUST_CHANGE, DEFAULT_DATABASE=Chapter10, 
    CHECK_EXPIRATION=ON, CHECK_POLICY=ON ;
GO

USE Chapter10
GO

CREATE USER Danielle FOR LOGIN Danielle ;
GO
