CREATE WORKLOAD GROUP InternalReports
    WITH(
        GROUP_MAX_REQUESTS=100, 
        IMPORTANCE=Medium, 
        REQUEST_MAX_CPU_TIME_SEC=0, 
        REQUEST_MAX_MEMORY_GRANT_PERCENT=25, 
        REQUEST_MEMORY_GRANT_TIMEOUT_SEC=0, 
        MAX_DOP=4
                ) USING ReportingApp ;
GO

CREATE WORKLOAD GROUP ExternalReports 
    WITH(
        GROUP_MAX_REQUESTS=100, 
        IMPORTANCE=Medium, 
        REQUEST_MAX_CPU_TIME_SEC=0, 
        REQUEST_MAX_MEMORY_GRANT_PERCENT=75, 
        REQUEST_MEMORY_GRANT_TIMEOUT_SEC=0, 
        MAX_DOP=8
        ) USING ReportingApp ;
GO

ALTER RESOURCE GOVERNOR RECONFIGURE;
GO
