ALTER DATABASE [Chapter6] ADD FILEGROUP [Chapter6_InMemory] CONTAINS MEMORY_OPTIMIZED_DATA;
GO

ALTER DATABASE [Chapter6] ADD FILE ( NAME = N'InMemory', FILENAME = N'F:\MSSQL\MSSQL15.PROSQLADMIN\MSSQL\DATA\InMemory' ) TO FILEGROUP [Chapter6_InMemory];
GO
